const { chromium } = require('../browser').pw;
const fs = require('fs');
const html = fs.readFileSync(require('path').join(__dirname,'..','..','index.html'), 'utf8').replace('boot();\n})();\n</script>', 'boot();\nwindow.T={S,LOCK,appLock};\n})();\n</script>');
const ok = (c, m) => console.log((c ? 'PASS ' : 'FAIL ') + m); let bodies = [];
(async () => {
  const b = await chromium.launch({ executablePath: require('../browser').exe });
  const ctx = await b.newContext({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 }); const p = await ctx.newPage();
  p.on('pageerror', e => console.log('PAGEERR', e.message));
  const cdp = await ctx.newCDPSession(p); await cdp.send('WebAuthn.enable');
  const { authenticatorId } = await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  await p.route('https://gupta.test/**', r => r.fulfill({ body: html, contentType: 'text/html' }));
  await p.route('https://script.google.com/**', r => { const q = r.request(); const send = o => r.fulfill({ body: JSON.stringify(o), contentType: 'application/json' });
    if (q.method() === 'GET') return send({ ok: true, rev: '1', bl: '0', bt: '0', items: [{ id: 'i1', name: 'PP Bag', unit: 'kg', buy: 100, sell: 120 }], config: { shopName: 'Gupta Plastics', mode: 'live' }, sv: 34 });
    const bd = JSON.parse(q.postData()); bodies.push(bd);
    if (bd.action === 'takeBill') return send({ ok: true, n: bd.n });
    return send({ ok: true, me: { name: 'Dad', role: 'manager', personal: true, prefs: {} }, tok: bd.wantTok ? 'tokD' : undefined }); });
  await p.goto('https://gupta.test/index.html'); await p.waitForTimeout(1500);
  await p.screenshot({ path: require('os').tmpdir() + '/lock-signin.png' });
  await p.fill('#al-pin', '2222'); await p.click('#al-go'); await p.waitForTimeout(900);
  ok(await p.evaluate(() => !!document.querySelector('#al-by')), 'after first PIN sign-in: offers fingerprint');
  await p.screenshot({ path: require('os').tmpdir() + '/lock-bioask.png' });
  await p.click('#al-by'); await p.waitForTimeout(800);
  const a = await p.evaluate(() => JSON.parse(localStorage.getItem('rb_auth')));
  ok(a.bio && !(await p.evaluate(() => document.documentElement.classList.contains('locked'))), 'fingerprint registered, app open');
  await p.evaluate(() => T.appLock()); await p.waitForTimeout(400);
  await p.screenshot({ path: require('os').tmpdir() + '/lock-pin.png' });
  await p.waitForTimeout(1200);
  ok(!(await p.evaluate(() => document.documentElement.classList.contains('locked'))), 'locked again: fingerprint opens it (no PIN typed)');
  await cdp.send('WebAuthn.setUserVerified', { authenticatorId, isUserVerified: false });
  await p.evaluate(() => T.appLock()); await p.waitForTimeout(1500);
  ok(await p.evaluate(() => document.documentElement.classList.contains('locked')) && /Use your PIN/.test(await p.textContent('#al-err')), 'fingerprint fails: stays locked, asks for PIN');
  for (const d of '2222') await p.click(`#al-pad [data-k="${d}"]`); await p.waitForTimeout(700);
  ok(!(await p.evaluate(() => document.documentElement.classList.contains('locked'))), 'PIN still works as the fallback');
  await b.close();
})();
