const { chromium } = require('../browser').pw;
const fs = require('fs');
const html = fs.readFileSync(require('path').join(__dirname,'..','..','index.html'), 'utf8').replace('boot();\n})();\n</script>', 'boot();\nwindow.T={appUnlock,openSettings,openVendors,get STK(){return SHEET_STK;}};\n})();\n</script>');
const ok = (c, m) => console.log((c ? 'PASS ' : 'FAIL ') + m);
const users = [{ id: 'u1', name: 'Sanjay', role: 'staff', active: true, testOk: true }, { id: 'u2', name: 'Dad', role: 'manager', active: true, testOk: true }];
const vendors = Array.from({ length: 30 }, (_, i) => ({ id: 'v' + i, name: 'Vendor ' + i, mobile: '', opening: 0, creditDays: 0, updatedAt: 100 - i }));
(async () => {
  const b = await chromium.launch({ executablePath: require('../browser').exe });
  const p = await (await b.newContext({ viewport: { width: 390, height: 780 } })).newPage(); p.on('pageerror', e => console.log('PAGEERR', e.message));
  await p.route('https://rb.test/**', r => r.fulfill({ body: html, contentType: 'text/html' }));
  await p.route('https://script.google.com/**', r => { const q = r.request(); const send = o => r.fulfill({ body: JSON.stringify({ ok: true, ...o }), contentType: 'application/json' });
    if (q.method() === 'GET') return send({ rev: '1', items: [], config: { shopName: 'Gupta Plastics', mode: 'live' }, sv: 34 });
    const bd = JSON.parse(q.postData());
    if (bd.action === 'verify') return send({ me: { name: 'Mayank', role: 'owner', personal: true, prefs: {} } });
    if (bd.action === 'listUsers' || bd.action === 'saveUser') return send({ users });
    if (bd.action === 'getAccess') return send({ access: { on: false } });
    if (bd.action === 'listSessions') return send({ sessions: [] });
    if (bd.action === 'backupInfo') return send({ info: { backups: [] } });
    if (bd.action === 'vSync') return send({ vrev: '1', vendors, entries: [] });
    return send({}); });
  await p.addInitScript(() => localStorage.setItem('rb_auth', JSON.stringify({ tok: 't', by: 'Mayank', role: 'owner', personal: true, pinH: 'x', pinS: 'AAAA' })));
  await p.goto('https://rb.test/index.html'); await p.waitForTimeout(1200); await p.evaluate(() => T.appUnlock());
  const sc = () => p.evaluate(() => document.querySelector('#sheet-body').scrollTop);
  const title = () => p.textContent('#sheet-title');
  const backBtn = () => p.evaluate(() => !document.querySelector('#sheet-back').hidden);
  // Settings: scroll to People, edit Sanjay
  await p.evaluate(() => T.openSettings()); await p.waitForTimeout(800);
  ok(await p.evaluate(() => [...document.querySelectorAll('details.cg')].every(d => !d.open)), 'Settings opens with every group closed');
  await p.click('details[data-cg="ppl"] summary'); await p.waitForTimeout(300);
  await p.evaluate(() => document.querySelector('[data-ppl="u1"]').scrollIntoView({ block: 'center' })); await p.waitForTimeout(200);
  const y0 = await sc(); ok(y0 > 300, `Settings scrolled down to People (scroll ${y0})`);
  await p.click('[data-ppl="u1"]'); await p.waitForTimeout(300);
  ok(await title() === 'Sanjay' && await backBtn(), 'Edit person opens with a ← back button in the header');
  await p.click('#sheet-back'); await p.waitForTimeout(300);
  ok(await title() === 'Settings' && Math.abs(await sc() - y0) < 3, 'header ← : back to Settings at the same scroll');
  await p.click('[data-ppl="u1"]'); await p.waitForTimeout(300); await p.click('#pp-cancel'); await p.waitForTimeout(300);
  ok(await title() === 'Settings' && Math.abs(await sc() - y0) < 3, 'Cancel: back to Settings at the same scroll');
  await p.click('[data-ppl="u1"]'); await p.waitForTimeout(300); await p.evaluate(() => { history.pushState({}, ''); history.back(); }); await p.waitForTimeout(500);
  ok(await title() === 'Settings' && Math.abs(await sc() - y0) < 3, "phone's Back: back to Settings at the same scroll");
  ok(await p.evaluate(() => { document.querySelector('#cf-shop').value = 'typed'; return true; }), '(typed into Settings before opening a child)');
  await p.click('[data-ppl="u1"]'); await p.waitForTimeout(300); await p.click('#sheet-back'); await p.waitForTimeout(200);
  ok(await p.inputValue('#cf-shop') === 'typed', 'going back keeps what was typed on Settings');
  await p.click('[data-ppl="u1"]'); await p.waitForTimeout(300); await p.click('#pp-save'); await p.waitForTimeout(1200);
  ok(await title() === 'Settings' && Math.abs(await sc() - y0) < 40, `Save: back to a fresh Settings near the same place (scroll ${await sc()})`);
  ok(await p.evaluate(() => T.STK.length) === 0, 'stack is back to one level');
  await p.click('[data-ppl="u1"]'); await p.waitForTimeout(300); await p.click('#sheet-close'); await p.waitForTimeout(400);
  ok(await p.evaluate(() => document.querySelector('#sheet').hidden), '✕ closes everything');
  await p.evaluate(() => T.openSettings()); await p.waitForTimeout(500); ok(!(await backBtn()), 'Settings opened fresh from Tools: no ← (nothing under it)');
  await p.click('details[data-cg="items"] summary'); await p.waitForTimeout(200); await p.click('#cf-groups'); await p.waitForTimeout(400); await p.click('#gr-cancel'); await p.waitForTimeout(300);
  ok(await title() === 'Settings', 'Groups → Cancel goes back to Settings (used to close everything)');
  await p.click('#sheet-close'); await p.waitForTimeout(400);
  // Vendors: scroll the list, open one, back
  await p.evaluate(() => T.openVendors()); await p.waitForTimeout(800);
  await p.evaluate(() => document.querySelector('[data-vid="v20"]').scrollIntoView({ block: 'center' })); const y1 = await sc();
  await p.click('[data-vid="v20"]'); await p.waitForTimeout(500); ok(await title() === 'Vendor 20', 'vendor opened');
  await p.click('#sheet-back'); await p.waitForTimeout(600);
  ok(await title() !== 'Vendor 20' && Math.abs(await sc() - y1) < 40, `vendor ← : back to the list near the same place (${y1} → ${await sc()})`);
  await b.close();
})();
